return {
    "A.D.I.D.A.S.",
    "AC DC - Back in Black.mid",
    "Avenged Sevenfold - Bat Country",
    "BeQuickOrBeDead",
    "Bitchslap",
    "Blind",
    "CaughtSomewhereInTime",
    "Clown",
    "Disasterpiece",
    "Duality",
    "Eyeless",
    "Faget",
    "FreakOnALeash",
    "Gentley",
    "GoodGod",
    "HereToStay",
    "Master of Puppets",
    "PhantomOfTheOpera",
    "Powerslave",
    "PrisonSong",
    "Revenga",
    "Slipknot - Psychosocial (ver 8 by Thaynan).mid",
    "Sugar",
    "ThunderStruck - ACDC",
    "Unholy Confessions"
}
