return {
    "A Little Piece of Heaven - Avenged Sevenfold (With vocals).mid",
    "A.D.I.D.A.S.",
    "AC DC - Back in Black.mid",
    "ACDC - Back in Black (3) [MIDIfind.com]",
    "Avenged Sevenfold - Almost Easy",
    "Avenged Sevenfold - Bat Country",
    "Avenged Sevenfold - Dear God.mid",
    "Avenged Sevenfold~Critical Acclaim",
    "BeQuickOrBeDead",
    "Bitchslap",
    "Blind",
    "CaughtSomewhereInTime",
    "Clown",
    "Disasterpiece",
    "Drum - Heavy Metal Drums [MIDIfind.com]",
    "Duality",
    "Eyeless",
    "Faget",
    "FreakOnALeash",
    "Gentley",
    "GoodGod",
    "HereToStay",
    "I Won't See You Tonight - Avenged Sevenfold",
    "Master of Puppets",
    "Megadeth - Holy Wars",
    "Meshuggah- Bleed.mid",
    "Metallica - Battery (2) [MIDIfind.com]",
    "PhantomOfTheOpera",
    "Powerslave",
    "PrisonSong",
    "Revenga",
    "Scream",
    "Slipknot - Psychosocial (ver 8 by Thaynan).mid",
    "Slipknot - Scissors [MIDIfind.com]",
    "Sugar",
    "ThunderStruck - ACDC",
    "Unholy Confessions"
}
