return {
    "505",
    "AllTheSmallThings",
    "AmericanIdiot",
    "Arctic Monkeys - Do I Wanna Know [MIDIfind.com]",
    "Arctic Monkeys - R U Mine [MIDIfind.com]",
    "BoysDontCry",
    "BreakStuff",
    "Come as you are (3 beats)",
    "Counterfeit",
    "Creep",
    "Degenerate",
    "Faith",
    "Foo Fighters - Everlong",
    "Girlfriend",
    "imagine-dragons-believer-drum-score",
    "Korn - Embrace",
    "Leech",
    "Linkin Park - No More Sorrow",
    "Linkin Park - Numb",
    "Rollin",
    "Smells Like Teen Spirit - Drums",
    "Weezer - Undone the Sweater Song [MIDIfind.com]"
}
