return {
    " NieR Automata -- Emil (Despair) ",
    "200 AniSong Medley HalcyonMusic",
    "AIZO HalcyonMusic",
    "audio2midi",
    "Beastars - JUNO is in love -adult-",
    "DEAD OR LIE",
    "Eldoraudio-Juan Arenosa - Ofelia  Official Music Video  - Juan Arenosa  128k  humanized",
    "Fukashigi no Carte",
    "Giornos Theme",
    "HalcyonMusic 10k subs medley",
    "If I am with you",
    "If I Am With You  Yoshimasa Terui  Jujutsu Kaisen S2 OST LB7",
    "IRIS OUT HalcyonMusic",
    "itterasshai-attack-on-titan-ss4-ed-ai-higuchi",
    "Jojo's Bizarre Adventure Part 2   Battle Tendency OP - Bloody Stream",
    "Josuke's theme Diamond Is Unbreakable in piano(COMPLETE)",
    "Judas",
    "Kamado Nezuko no Uta HalcyonMusic",
    "Kensuke Ushio - IN THE POOL",
    "Kensuke Ushio - in the pool v2",
    "Kensuke Ushio - in the pool v3",
    "Kimi no Na wa    Sparkle  TheIshter  Full Sheets 1772654410756",
    "Mermaid Rhapsody – v3rmillionkyo",
    "Never Meant To Belong - Bleach",
    "Never Meant To Belong (Bleach OST)",
    "New Darling",
    "Nezuko HalcyonMusic",
    "NieR - Kaine Salvation",
    "Orange 7!! - Your Lie In April",
    "pf solo",
    "Self Embodiment of Perfection (Mahito Theme)",
    "Shinzou wo Sasageyo HalcyonMusic",
    "shock-attack-on-titan-ed6",
    "Sono Chi No Sadame - Jojo's Bizarre Adventure",
    "Summer Pockets",
    "Sword Art Online Medley HalcyonMusic",
    "Throughout heaven and earth, i alone am the honored one",
    "Tokyo Ghoul - Unravel",
    "utsukushiki-zankoku-na-sekai-attack-on-titanshingeki-no-kyojin-ed-1-full",
    "Vickeblanka - Black Catcher Black Clover Opening 10 WT1",
    "Yoshimasa Terui - IF I AM WITH YOU",
}
