return {
    "200 AniSong Medley HalcyonMusic",
    "AIZO HalcyonMusic",
    "audio2midi",
    "Beastars - JUNO is in love -adult-",
    "DEAD OR LIE",
    "Eldoraudio-Juan Arenosa - Ofelia  Official Music Video  - Juan Arenosa  128k  humanized",
    "Fukashigi no Carte",
    "Giornos Theme",
    "HalcyonMusic 10k subs medley",
    "If I am with you",
    "If I Am With You  Yoshimasa Terui  Jujutsu Kaisen S2 OST LB7",
    "itterasshai-attack-on-titan-ss4-ed-ai-higuchi",
    "Josuke's theme Diamond Is Unbreakable in piano(COMPLETE)",
    "Judas",
    "Kensuke Ushio - IN THE POOL",
    "Kimi no Na wa    Sparkle  TheIshter  Full Sheets 1772654410756",
    "Mermaid Rhapsody – v3rmillionkyo",
    "Never Meant To Belong - Bleach",
    "Never Meant To Belong (Bleach OST)",
    "New Darling",
    "pf solo",
    "shock-attack-on-titan-ed6",
    "Summer Pockets",
    "Sword Art Online Medley HalcyonMusic",
    "Tokyo Ghoul - Unravel",
    "utsukushiki-zankoku-na-sekai-attack-on-titanshingeki-no-kyojin-ed-1-full",
    "Vickeblanka - Black Catcher Black Clover Opening 10 WT1",
    "Yoshimasa Terui - IF I AM WITH YOU",
}
