return {
    "ABBA - The Winner Takes it All",
    "Adele - Skyfall",
    "AnyConv.com  5875-ed88-4b61-9772-980efa64c95d",
    "Arabesque-in-E-Nr-1",
    "Beethoven - Moonlight Sonata (1st Movement) ",
    "Beethoven Virus (insane)",
    "Beethoven Virus (insane).mid (1)",
    "Bruno Mars - Risk It All",
    "Chopin – Nocturne Op.9 No.2",
    "chopin ballade 4 (c)lubetsky",
    "Counting stars",
    "Dạo Bước HongKong 1999",
    "Flamewall",
    "Fur Elise (1)",
    "Gloria Gaynor Arr.  Elaine Kelkel - I Will Survive",
    "in the pool  C",
    "JOPLIN.The entertainer",
    "liebestraum",
    "Merry-Go-Round of Life  Animenz",
    "MIDI File - Bruno Mars - Risk It All (Easy)",
    "moonlight-sonata-i",
    "MỘT ĐỜI (14 Casper & Bon Nghiêm)",
    "operas",
    "Pirates of the Caribbean - He's a Pirate (1)",
    "Risk it all",
    "Rush E but its as difficult as humanly possible",
    "Summer",
    "بروحي فتاة.",
    "กลัวว่าฉันจะไม่เสียใจ (Fear) – PURPEECH",
}
