return {
    "ABBA - The Winner Takes it All",
    "Adele - Skyfall",
    "AnyConv.com  5875-ed88-4b61-9772-980efa64c95d",
    "Arabesque-in-E-Nr-1",
    "Beethoven Virus (insane)",
    "Beethoven Virus (insane).mid (1)",
    "Bruno Mars - Risk It All",
    "chopin ballade 4 (c)lubetsky",
    "Dạo Bước HongKong 1999",
    "Flamewall",
    "Gloria Gaynor Arr.  Elaine Kelkel - I Will Survive",
    "in the pool  C",
    "liebestraum",
    "Merry-Go-Round of Life  Animenz",
    "MIDI File - Bruno Mars - Risk It All (Easy)",
    "moonlight-sonata-i",
    "Pirates of the Caribbean - He's a Pirate (1)",
    "Risk it all",
    "Summer",
    "بروحي فتاة.",
}
