return {
    "a good man with a broken heart - lovibe",
    "Back To Friends - Sombr",
    "D4vd Romantic Homicide piano midi",
    "Elton John - I'm still standing",
    "Hope - XXXTENTACION",
    "I Deserve To Bleed - Suchi Soucy",
    "Interstellar main theme (With Effects!)",
    "Laufey - Promise",
    "Like Him Tyler The Creator",
    "Moonlight - XXXTentacion",
    "Multo - Cup of Joe RNE",
    "Øneheart & reidenshi snowfall piano midi",
    "PULSE  Tony Ann aka my neighbours car alarm 1770203303452",
    "Tally Hall- Hidden in the Sand ",
    "Tony Ann - ICARUS",
    "Tony Ann - Reminisce 2",
    "Washing Machine Heart - Mitski",
    "Wave to earth - Love",
    "Where's My Love – SYML",
}
