return {
    "111219 jack-stauber-baby-hotline f7v8 musicboxmaniacs.com",
    "a good man with a broken heart - lovibe",
    "Baby Hotline",
    "Back To Friends - Sombr",
    "Buttercup - Jack Stauber",
    "Childish Gambino - Redbone",
    "Credits Song For My Death",
    "D4vd Romantic Homicide piano midi",
    "Elton John - I'm still standing",
    "Hope - XXXTENTACION",
    "I Deserve To Bleed - Suchi Soucy",
    "Interstellar main theme (With Effects!)",
    "Jack Stauber - Baby Hotline (5)",
    "KISS — I Was Made For Loving You",
    "Laufey - Promise",
    "like him - tyler creator",
    "Like Him Tyler The Creator",
    "Lost Sky - Dreams Pt. II",
    "Moonlight - XXXTentacion",
    "Multo - Cup of Joe RNE",
    "Øneheart & reidenshi snowfall piano midi",
    "PULSE  Tony Ann aka my neighbours car alarm 1770203303452",
    "Tally Hall- Hidden in the Sand ",
    "Tony Ann - ICARUS",
    "Tony Ann - Reminisce 2",
    "Washing Machine Heart - Mitski",
    "Wave to earth - Love",
    "Where's My Love – SYML",
}
