return {
    "ASGORE - Toby Fox",
    "Battle Against a True Hero (Undyne the Undying) (wip)",
    "Doki Doki Literature Club - Main Theme - ShinkoNetCavy",
    "Fallen Down - Toby Fox",
    "Fallen down (Reprise)",
    "Finale - Toby Fox",
    "Gaster's Theme - Toby Fox",
    "MEGALOVANIA - Toby Fox",
    "Metal Crusher",
    "my light (我的光) - yung kai",
    "sans. - Toby Fox",
    "Snowy - Toby Fox",
    "Stronger Than You - Undertale",
    "Thick Of It [The one from IG reels]",
    "Undertale - SAVE the World",
    "Undertale - Toby Fox",
    "Your Reality",
}
