return {
    " Until-Then-OST--Memories",
    "Animation Warrior Theme - Nighthawk22",
    "ASGORE - Toby Fox",
    "Back on Track",
    "Basics in behavior",
    "Battle Against a True Hero (Undyne the Undying) (wip)",
    "C418 - Mice on Venus",
    "C418 - Subwoofer Lullaby",
    "Creo - Flow",
    "Dialtone - MIDI",
    "Doki Doki Literature Club - Main Theme - ShinkoNetCavy",
    "Fallen Down - Toby Fox",
    "Fallen down (Reprise)",
    "Finale - Toby Fox",
    "finale-undertale",
    "Five nights at Freddy's Song",
    "Gaster's Theme - Toby Fox",
    "KEY AFTER KEY LMS",
    "Legend Of Zelda - Saria's Song",
    "MEGALOVANIA - Toby Fox",
    "Metal Crusher",
    "Mili - Compass",
    "Mili - Fly, My Wings",
    "Mili - Hero",
    "Mili - Through Patches of Violet",
    "my light (我的光) - yung kai",
    "NieR - Song of the Ancients Devola",
    "Peaches - Jack Black (from the Super Mario Bros. Movie)",
    "PHOENIX LMS",
    "Red Battle - Pokémon Gold Silver",
    "Rush stereo madness",
    "sans. - Toby Fox",
    "Shiawase Vip",
    "Snowy - Toby Fox",
    "Stereo madness",
    "Stereo Madness - ForeverBound",
    "Stronger Than You - Undertale",
    "Tetris Theme, BLACK MIDI 50K NOTES",
    "Thick Of It [The one from IG reels]",
    "Undertale - SAVE the World",
    "Undertale - Toby Fox",
    "Uwa!! So Temperate♫ (UNDERTALE)",
    "Your Reality",
}
