return {
    "Animation Warrior Theme - Nighthawk22",
    "ASGORE - Toby Fox",
    "Battle Against a True Hero (Undyne the Undying) (wip)",
    "C418 - Mice on Venus",
    "Creo - Flow",
    "Doki Doki Literature Club - Main Theme - ShinkoNetCavy",
    "Fallen Down - Toby Fox",
    "Fallen down (Reprise)",
    "Finale - Toby Fox",
    "finale-undertale",
    "Gaster's Theme - Toby Fox",
    "MEGALOVANIA - Toby Fox",
    "Metal Crusher",
    "Mili - Compass",
    "Mili - Fly, My Wings",
    "Mili - Hero",
    "Mili - Through Patches of Violet",
    "my light (我的光) - yung kai",
    "Peaches - Jack Black (from the Super Mario Bros. Movie)",
    "Red Battle - Pokémon Gold Silver",
    "sans. - Toby Fox",
    "Shiawase Vip",
    "Snowy - Toby Fox",
    "Stereo Madness - ForeverBound",
    "Stronger Than You - Undertale",
    "Thick Of It [The one from IG reels]",
    "Undertale - SAVE the World",
    "Undertale - Toby Fox",
    "Your Reality",
}
