return {
    "abcdefu",
    "Bad Habit - Steve Lacy",
    "basic pitch transcription",
    "Beanie",
    "blue - yung kai",
    "Country Roads",
    "Die with a smile - Piano Solo LKZ",
    "Her - JVKE",
    "iris-goo-goo-dolls",
    "Mitski - My Love Mine All Mine",
    "mrs magic",
    "Tek It - Cafune",
    "Tony Ann - Anxiety",
    "Young Girl A - siinamota (slightly more difficult)",
    "بروحي فتاة.",
}
