return {
    "Ai Đưa Em Về (Take Me Back Home) – TIA  feat. Lê Thiện Hiếu (Low Cortisol Song)",
    "Alan Walker - Alone Part II",
    "Bad Habit - Steve Lacy",
    "banh mi Khong",
    "basic pitch transcription",
    "Beanie",
    "Beggin' – Måneskin Drum Sheet Music",
    "blue - yung kai",
    "Camellia - Flamewall",
    "coffin nails   rapp snitch knishes",
    "Congratulations - Mac Miller (Final Project)",
    "Counting Stars by OneRepublic - Drums",
    "Country Roads",
    "Credits Song For My Death (Code: 900)",
    "Die with a smile - Piano Solo LKZ",
    "Dimension Creo",
    "Elton John - I'm Still Standing (Expert)",
    "Golden Brown Arragement By natsu",
    "Guns N Roses - Sweet Child O' Mine (1)",
    "Her - JVKE",
    "How The World Works - Bo Burnham",
    "In the end drum",
    "iris-goo-goo-dolls",
    "Mitski - My Love Mine All Mine",
    "mrs magic",
    "Night Changes Piano Arr 1775503451731",
    "No batidão impossible",
    "Nơi này có anh impossible",
    "rapp snitch knishes",
    "Rapp Snitch Knishes - MF DOOM",
    "Strawberry Guy - Mrs Magic (Strings Version)",
    "Tek It - Cafune",
    "The+New+Periodic+Table+Song",
    "TheFatRat+-+Windfall",
    "Tony Ann - Anxiety",
    "بروحي فتاة.",
}
