return {
    "87560 Cause-I-love-you",
    "Bruno Mars - When i was your man",
    "buông đôi tay nhau ra x nắng ấm xa dần",
    "cause i love you x gạt đi nc mắt",
    "chắc ai đó sẽ về",
    "Chờ_đợi_có_đáng_sợ",
    "cocktail",
    "cơn mưa ngang qua",
    "Golden Hour  JVKE Updated Ver 1772653873814",
    "Gravity - Hazbin Hotel",
    "hãy trao cho anh",
    "Hello- OMFG (WIP)(Copy)",
    "id 072019",
    "Interstellar x Experience",
    "Never-Gonna-Give-You-Up-3",
    "những lời hứa bỏ quên ost",
    "NOSTALGIA  Tony Ann 1769819486012",
    "RUSH_F",
    "Rush_of_Life_-_Tony_Ann",
    "tháng 4là lời nói dối của em",
    "Tony Ann - Awakening",
    "Tony Ann - Desire",
    "Tony Ann - Discovery",
    "Tony Ann - Lost",
    "Tony Ann - Pulse",
    "Tony Ann - Rain",
    "Tony Ann Taurus",
    "trillium",
    "vết mưa",
    "Wind Of Fjords - Soft Knees",
    "Worlds Smallest Violin full notes",
}
