return {
    " Erika  A German WW2 marching song",
    "*I've Lived for 1000 Years / Living millennium - Iyowa* mhxa",
    "6 TRILLION YEARS AND AN OVERNIGHT STORY mhxa",
    "A Tale of SIX Trillion years and night  mhxa",
    "Bad Apple - touhou - midi by tutogamer2a - final version",
    "Beta0404",
    "Broken World mhxa",
    "Bruno Mars - When i was your man",
    "buông đôi tay nhau ra x nắng ấm xa dần",
    "cause i love you x gạt đi nc mắt",
    "Celestial Opus",
    "chắc ai đó sẽ về",
    "Chờ đợi có đáng sợ",
    "cocktail",
    "coffin nails   rapp snitch knishes",
    "CupofJoe & Multo mhxa",
    "drag-me-down-twenty-one-two",
    "Engravings mhxa",
    "EnterSandman",
    "Ethan Bortnick - cut my fingers off",
    "Every Living Breathing Moment mhxa",
    "Golden Hour  JVKE Updated Ver 1772653873814",
    "Gooseworx - Your New Home MIDI (Your Piano Tutorials)",
    "Gravity - Hazbin Hotel",
    "Gravity (from Hazbin Hotel)",
    "Guns N Roses - Sweet Child O' Mine",
    "hãy trao cho anh",
    "Hello- OMFG (WIP)(Copy)",
    "HELP!! Kobo kanaeru* mhxa",
    "id 072019",
    "Interstellar x Experience",
    "iris-goo-goo-dolls",
    "JVKE golden hour piano mhxa",
    "JVKE her mhxa",
    "Kaijuu Ni Naritai",
    "Looping The Rooms mhxa",
    "Metallica-Enter-Sandman midi",
    "Michael Jackson - Billie Jean",
    "MrKitty-After-Dark-rlc-winston-20211103115423-nonstop2k.com",
    "Mundo x Your universe mhxa",
    "natori - sarushibai mhxa",
    "natori - serenade mhxa",
    "Natori propose mhxa",
    "Never-Gonna-Give-You-Up-3",
    "nguyện cầu đến 50 năm",
    "những lời hứa bỏ quên ost",
    "Night of Knights Lunatic mhxa",
    "no name (7)",
    "NOSTALGIA  Tony Ann 1769819486012",
    "not yours",
    "oi josuke",
    "One Direction Night Changes ADVANCED",
    "Rush Among Us 2",
    "RUSH B - ReBlacked",
    "Rush C# 3",
    "rush e",
    "Rush E (1.2M Notes)",
    "Rush E 2 (Impossible) (1)",
    "RUSH E 2 but its HAPPY",
    "rush e 3",
    "Rush E 4 Black Midi By S3G",
    "Rush E boss? mhxa",
    "RUSH E but something is OFF!",
    "RUSH F",
    "Rush of Life - Tony Ann",
    "sinkingtown",
    "Somewhere Only We Know ADVANCED",
    "Tally Hall - The Bidding",
    "tháng 4là lời nói dối của em",
    "the entertainer",
    "the-real-slim-shady-eminem",
    "Theatre mhxa",
    "this is the talking",
    "this is what falling in love feels like JVKE",
    "Tokyo Ghoul Unravel",
    "Tony Ann - Awakening",
    "Tony Ann - Desire",
    "Tony Ann - Discovery",
    "Tony Ann - Lost",
    "Tony Ann - Pulse",
    "Tony Ann - Rain",
    "Tony Ann Taurus",
    "Touhou Bad Apple mhxa",
    "Touhou Owen was her v1 mhxa",
    "Touhou Owen was her V2 mhxa",
    "trillium",
    "Vaundy - Odoriko mhxa",
    "Want to be Crem#ted/Ab#se mhxa",
    "We're Going To Be Friends (WIP)",
    "White Stripes (The) — We Re Going to Be Friends [MIDIfind.com]",
    "Wind Of Fjords - Soft Knees",
    "Worlds Smallest Violin full notes",
    "Young Girl A mhxa",
    "Yurima - River flows in you mhxa",
}
