return {
    "Bad Apple - touhou - midi by tutogamer2a - final version",
    "Beta0404",
    "Bruno Mars - When i was your man",
    "buông đôi tay nhau ra x nắng ấm xa dần",
    "cause i love you x gạt đi nc mắt",
    "chắc ai đó sẽ về",
    "Chờ đợi có đáng sợ",
    "cocktail",
    "drag-me-down-twenty-one-two",
    "Golden Hour  JVKE Updated Ver 1772653873814",
    "Gravity - Hazbin Hotel",
    "hãy trao cho anh",
    "Hello- OMFG (WIP)(Copy)",
    "id 072019",
    "Interstellar x Experience",
    "iris-goo-goo-dolls",
    "Michael Jackson - Billie Jean",
    "Never-Gonna-Give-You-Up-3",
    "những lời hứa bỏ quên ost",
    "NOSTALGIA  Tony Ann 1769819486012",
    "R U Mine",
    "Rush Among Us 2",
    "RUSH B - ReBlacked",
    "Rush C# 3",
    "RUSH E 2 but its HAPPY",
    "RUSH E but something is OFF!",
    "RUSH F",
    "Rush of Life - Tony Ann",
    "tháng 4là lời nói dối của em",
    "the-real-slim-shady-eminem",
    "this is the talking",
    "Tony Ann - Awakening",
    "Tony Ann - Desire",
    "Tony Ann - Discovery",
    "Tony Ann - Lost",
    "Tony Ann - Pulse",
    "Tony Ann - Rain",
    "Tony Ann Taurus",
    "trillium",
    "Wind Of Fjords - Soft Knees",
    "Worlds Smallest Violin full notes",
}
