name: Create Return Files

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-returnfiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create returnfiles
        run: |
          mkdir -p GuitarPresets/returnfiles

          echo "return {}" > GuitarPresets/returnfiles/Animereturn.lua
          echo "return {}" > GuitarPresets/returnfiles/GameOSTreturn.lua
          echo "return {}" > GuitarPresets/returnfiles/Classicalreturn.lua
          echo "return {}" > GuitarPresets/returnfiles/Modernreturn.lua
          echo "return {}" > GuitarPresets/returnfiles/Rockreturn.lua

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Create returnfiles for categories" || echo "No changes to commit"
          git push
